language: node_js
node_js:
  - "9"
cache:
  directories:
    - $HOME/.cache/yarn
    - .cache
dist: trusty
os:
  - linux
script:
  - yarn test
before_deploy: rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: o99xXQsrBR+tQwsyV8dM8Ia0JnpewWsCNQD/DUAW40Y82sRmCikI6k87kHHY1uHuZ30t9X5Slo+fI/9psEGfE0PGdkfMV99rzl1qVKrLeOLWTz8fNGapZtg1Ahjt1M5Ca23XJj1MRTXwAji/XP4KijiRrsMgBC3shlbvKNaWgbkzK1BTQVSMlMTJNY9ZT/tQ5tP4YljDfs0WYuXTXtAEl8ALf75NvQv2R9GQuDBGDALsJP/Vwr3FG+COJjq6YDFjpCKl6G90q2LwyfyL/bxJHCook+bVTMCOPrNmM1+HoiG7htBpHOakcpegiQlFDg4L4yfV+VFpSi9zzREVnjdnqsYKME0kmCC32kBw1viNqNnB8s6NYmYLRknMMvAVKZkQfGqS5hA/FM9Qt+3e5UdFmjs73uKavY159uMJIjHvR6+MHX0OVhyInW0xhBGrjyvLV8xV9ITsBAKLp11dkPYJgdDuFomsWzbML+6+x21R98vmdgUrIjPk8BXRiaBOtEfX15tBhcOk63lYa1WYSixuzFKjdRTB6JdURCVLTRgu4NV6TH7ZXRpHviXEMoGQJDBCrsLCEbd/zjXxMp/vE+cHnPS2228mVpr1oz9kFQ3HU9U2XcErKKJYLFjJaDKMLh/KQ2R3hrVq/c29XBfGTPR1jsUPyZS6Fg4N9vgt6ma1Rv8=
  app: apollo-universal-starter-kit
  on:
    repo: sysgears/apollo-universal-starter-kit
